// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushData.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace PushServer
{
  public static partial class PushService
  {
    static readonly string __ServiceName = "PushService";

    static readonly grpc::Marshaller<global::UserInfo> __Marshaller_UserInfo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::UserInfo.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ResponseInfo> __Marshaller_ResponseInfo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ResponseInfo.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SendMessageInfo> __Marshaller_SendMessageInfo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SendMessageInfo.Parser.ParseFrom);

    static readonly grpc::Method<global::UserInfo, global::ResponseInfo> __Method_Login = new grpc::Method<global::UserInfo, global::ResponseInfo>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Login",
        __Marshaller_UserInfo,
        __Marshaller_ResponseInfo);

    static readonly grpc::Method<global::SendMessageInfo, global::ResponseInfo> __Method_SendMessage = new grpc::Method<global::SendMessageInfo, global::ResponseInfo>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendMessage",
        __Marshaller_SendMessageInfo,
        __Marshaller_ResponseInfo);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PushDataReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PushService</summary>
    public abstract partial class PushServiceBase
    {
      public virtual global::System.Threading.Tasks.Task Login(global::UserInfo request, grpc::IServerStreamWriter<global::ResponseInfo> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ResponseInfo> SendMessage(global::SendMessageInfo request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PushService</summary>
    public partial class PushServiceClient : grpc::ClientBase<PushServiceClient>
    {
      /// <summary>Creates a new client for PushService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PushServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PushService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PushServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PushServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PushServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::ResponseInfo> Login(global::UserInfo request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::ResponseInfo> Login(global::UserInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Login, null, options, request);
      }
      public virtual global::ResponseInfo SendMessage(global::SendMessageInfo request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ResponseInfo SendMessage(global::SendMessageInfo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ResponseInfo> SendMessageAsync(global::SendMessageInfo request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ResponseInfo> SendMessageAsync(global::SendMessageInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendMessage, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PushServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PushServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PushServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Login, serviceImpl.Login)
          .AddMethod(__Method_SendMessage, serviceImpl.SendMessage).Build();
    }

  }
}
#endregion
